version: "3.7"

services:
  tasker_pg:
    image: postgres:15.1
    container_name: tasker_pg
    restart: always
    environment:
      POSTGRES_DB: tasker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret1234
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
  pg_admin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nestjs.com
      PGADMIN_DEFAULT_PASSWORD: secret1234
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
    volumes:
      - /var/lib/pgadmin
    depends_on:
      - tasker_pg